path: C:\Users\Shresth.Aggarwal\PycharmProjects\object_detection\Car_detector\data2 #dataset root directory #absolute path
train: images\train # train images (relative to 'path')
val: images\test # (relative to 'path')


#Classes
names:
  0: car
  1: no car