path: C:\Users\Shresth.Aggarwal\PycharmProjects\object_detection\Car_detector\data #dataset root directory #absolute path
train: images\training_images # train images (relative to 'path')
val: images\testing_images # (relative to 'path')


#Classes
names:
  0: car
  1: no car